### PR TITLE
282 Migrate to `shinytest2`

### LINKED ISSUE #282: Migrate to `shinytest2`
Motivation to switch from old `shinytest`:
- `phantomJS` does not work on Windows
- Chrome based and therefore has less quirks in general
- better API

To do:
- [x] Get familiar with `shinytest2`
	- [x] watch https://www.youtube.com/watch?v=Gucwz865aqQ
	- [x] read https://rstudio.github.io/shinytest2/articles/shinytest2.html and other vignettes as required
	- [x] read https://rstudio.github.io/shinytest2/articles/z-migration.html for migration details
- [x] run `shinytest2::migrate_from_shinytest(PATH_TO_APP)` for each test app in the tests folder
	- [ ] need to workaround by copy/pasting the `test_that()` content to separate file and then passing that to the function
- [ ] adjust results and fix test by test

This will fix #279 and #266

### PR DESCRIPTION
**Pull request by BFalquet**
closes #282, #266, #279 

creation of shinytests 2

thnak you for the review

### CODE REVIEW

File: tests/testthat/adtteSpec/.gitignore [hunk 1]
```diff
@@ -0,0 +1,2 @@
+# {shinytest2}: Ignore new debug snapshots for `$expect_values()`
+*_.new.png
```
Comment (danielinteractive) [inline tests/testthat/adtteSpec/.gitignore:2]: could this be ignored on higher-level `.gitignore` file ? so that we don't have to repeat for every test?

File: tests/testthat/adtteSpec/tests/testthat/test-shinytest2.R [hunk 2]
```diff
@@ -0,0 +1,51 @@
+library(shinytest2)
```
Comment (danielinteractive) [inline tests/testthat/adtteSpec/tests/testthat/test-shinytest2.R:1]: hm I guess you tried already, anyway asking - is there a way to have this file within the `tests/testthat` directory (so 3 folders up) or within the `tests/testthat/adtteSpec` directory? it feels like there are a lot of folders wrapped in each other now...

File: tests/testthat/adtteSpec/tests/testthat/test-shinytest2.R [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+  app$set_inputs(`teal-main_ui-root-adttespec_example-genes-genes` = character(0))
+  app$set_inputs(`teal-main_ui-root-adttespec_example-genes-fun_name` = "Mean")
+  app$set_inputs(`teal-main_ui-root-adttespec_example-adtte-paramcd` = "")
+  app$set_inputs(`teal-main_ui-root-adttespec_example-genes-lock_button` = FALSE)
+  app$expect_values()
+  app$set_inputs(`teal-main_ui-root-adttespec_example-genes-genes` = "GeneID:28")
+
+  # Upon initialization the endpoint is not selected automatically, the user
+  # has to click this actively.
+  app$expect_values()
```
Comment (danielinteractive) [inline tests/testthat/adtteSpec/tests/testthat/test-shinytest2.R:34]: I think in this test file there is too many blanket snapshot expectations. I would prefer more specific comparisons, see e.g. https://rstudio.github.io/shinytest2/articles/robust.html#example, so first getting specific values and then comparing those

**Review by danielinteractive — COMMENTED** [review]
thanks @BFalquet for your work on this, please see first comments inside

File: tests/testthat/adtteSpec/tests/testthat/test-shinytest2.R [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+  app$set_inputs(`teal-main_ui-filter_panel-add_ADTTE_filter-filter-var_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-var_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-row_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-col_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-row_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-col_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-row_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-col_to_add` = character(0))
+  app$set_inputs(`teal-main_ui-root-active_tab` = "adttespec_example")
+  app$click("teal-main_ui-root-adttespec_example-genes-select_none_button")
```
Comment (danielinteractive) [inline tests/testthat/adtteSpec/tests/testthat/test-shinytest2.R:17]: let's try to use e.g. `$set_inputs(!!input := "click")` etc.

**Review by danielinteractive — COMMENTED** [review]
nice thanks Benoit, looks good like this!!

**Comment by BFalquet** [comment]
> nice thanks Benoit, looks good like this!!

thanks I ll continue in this direction.

File: tests/testthat/test-shinytest2-adtteSpec.R [hunk 5]
```diff
@@ -0,0 +1,48 @@
+library(shinytest2)
+
+test_that("{shinytest2} recording: adtteSpecServer module works as expected in the test app", {
+  app <- AppDriver$new(
+    app_dir = "adtteSpec",
+    name = "adtteSpecServer module works as expected in the test app",
+    height = 520, width = 979
```
Comment (danielinteractive) [inline tests/testthat/test-shinytest2-adtteSpec.R:7]:
```suggestion
```

**Comment by BFalquet** [comment]
I have left the original test files associated with particular modules  for comparison purposes (so some test are duplicated for now), I ll remove them before converting the draft to actual PR

File: tests/testthat/adtteSpec/tests/testthat.R [hunk 6]
```diff
@@ -0,0 +1 @@
+shinytest2::test_app()
```
Comment (danielinteractive) [inline tests/testthat/adtteSpec/tests/testthat.R:1]: delete this file

File: tests/testthat/adtteSpec/tests/testthat/setup-shinytest2.R [hunk 7]
```diff
@@ -0,0 +1,2 @@
+# Load application support files into testing environment
```
Comment (danielinteractive) [inline tests/testthat/adtteSpec/tests/testthat/setup-shinytest2.R:1]: also this one

File: tests/testthat/test-shinytest2-adtteSpec.R [hunk 8]
```diff
@@ -0,0 +1,226 @@
...
+# adtteSpecInput ----
+
+test_that("adtteSpecInput creates expected HTML", {
+  expect_snapshot(adtteSpecInput(
+    "adtte",
+    label_paramcd = "Select right PARAMCD"
+  ))
+})
+
+test_that("{shinytest2} recording: adtteSpecServer module works as expected in the test app", {
```
Comment (danielinteractive) [inline tests/testthat/test-shinytest2-adtteSpec.R:179]:
```suggestion
test_that("adtteSpecServer module works as expected in the test app", {
```

File: tests/testthat/test-shinytest2-adtteSpec.R [hunk 9]
```diff
@@ -0,0 +1,226 @@
...
+  skip_if_covr()
+  skip_if_too_deep(5)
+
+  app <- AppDriver$new(
+    app_dir = "adtteSpec",
+    name = "adtteSpecServer module works as expected in the test app"
+  )
+  ns <- module_ns_shiny2(app)
+  ns2 <- NS("teal-main_ui-filter_panel")
```
Comment (danielinteractive) [inline tests/testthat/test-shinytest2-adtteSpec.R:188]: can put this centrally since it does not depend on the module

File: tests/testthat/test-shinytest2-adtteSpec.R [hunk 10]
```diff
@@ -0,0 +1,226 @@
...
+
+  res <- app$get_value(input = ns("adtte-paramcd"))
+
+  # Test what happens if selected endpoint (here PFS) is no longer in filtered data.
+  app$set_inputs(!!ns2("add_ADTTE_filter-filter-var_to_add") := "PARAMCD")
+  app$set_inputs(!!ns2("ADTTE_filter-filter-_var_PARAMCD-content-selection") := "OS")
+
+  app$wait_for_idle()
+  # We expect to get a validation message (also a notification box but we cannot test that)
+  res <- app$wait_for_value(output = ns("summary"))
```
Comment (danielinteractive) [inline tests/testthat/test-shinytest2-adtteSpec.R:216]:
```suggestion
  res <- app$get_value(output = ns("summary"))
```
? if it works

Comment (BFalquet) [reply tests/testthat/test-shinytest2-adtteSpec.R:216]: the pattern `app$wait_for_idle()` followed by `app$wait_for_value(...)` has been eliminated

File: tests/testthat/test-shinytest2-adtteSpec.R (hunk 9 above)
Comment (BFalquet) [reply tests/testthat/test-shinytest2-adtteSpec.R:188]: moved to  `helper-shinytest2.R`

File: tests/testthat/test-shinytest2-adtteSpec.R (hunk 8 above)
Comment (BFalquet) [reply tests/testthat/test-shinytest2-adtteSpec.R:179]: clean up completed

**Comment by danielinteractive** [comment]
@BFalquet  Maybe now is a good time to really replace the old files, so we can see the diff directly? thanks

**Comment by BFalquet** [comment]
Hi @danielinteractive , so you think we should change the testing depth? I have kept the same as previously but we could probably adjust it now.

**Review by danielinteractive — APPROVED** [review]

**Comment by nikolas-burkoff** [comment]
Please also add scda.2022 into the staged.deps yaml file (and as a suggests in the description file) - I've created https://github.com/insightsengineering/scda.2022/pull/91 which will go green once these changes have been made 👍
